version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/api
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data
  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    volumes:
      - ./:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis