:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  HackerNewsFetch:
    cron: '0 * * * * *'   # Runs once per minute
    class: RssFetch::HackerNewsJob